payara/Diagnostics-Tool

src/main/java/fish/payara/extras/diagnostics/asadmin/BaseAsadmin.java
src/main/java/fish/payara/extras/diagnostics/asadmin/CollectAsadmin.java

Structures the output file so that it includes a UTC timestamp and the domain name.
Also includes some cleanup - removing redundant Strings and fixing a javadoc error.
Testing done:
* Ran command against default domain: `collect-diagnostics --dir D:\Downloads\`
* Ran command against a non-default domain:
* `create-domain --portbase 5000 --nopassword test`
* `collect-diagnostics --dir D:\Downloads testy`
* Set computer timezone to UTC+2
* Ran diagnostic command, timestamp was still in UTC.
Output was in the format of `payara-diagnostics-${domainName}-2024-03-06THH-mm-ssZ`

FISH-8384 Structure Zip Name

---

src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java

Create the following directory in server logs `\logs\server\tx\recoveryfile`
Test before and after for collection.
Just checks to see if logs are actually logs and doesn't copy the .gitkeep file anymore.

FISH-8393 Fix Server Log Exception

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/util/DomainXmlUtil.java

Obfuscates the addresses and hosts in the domain.xml file. Address `'0.0.0.0'` and host `'localhost'` are kept. Along with this, if an address or host appears more than once, it will be named the same. for example, 2 instances of `1.2.3.4` would appear as `OBFUSCATED_HOST_X`.
Obfuscated jdbc url so it keeps the database type. for example, `jdbc:h2:xxxxx` is replaced by `jdbc:h2:database-obfuscated`.
A change has also been made to the directory creation for the zip file as it before used '\' and now it uses '/'. (last commit)
I have attached a link in the description in commit 12fa245.
To test I created new addresses in IIOP, Network Listeners and JMS Hosts, leaving some values default.
command used to test:
```
./asadmin collect-diagnostics
```

FISH-8177 obfuscate ip addresses hostnames in domain xml

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/util/DomainXmlUtil.java

(`Payara6`) Obfuscates the addresses and hosts in the domain.xml file. Address `'0.0.0.0'` and host `'localhost'` are kept. Along with this, if an address or host appears more than once, it will be named the same. for example, 2 instances of `1.2.3.4` would appear as `OBFUSCATED_HOST_X`.
Obfuscated jdbc url so it keeps the database type. for example, `jdbc:h2:xxxxx` is replaced by `jdbc:h2:database-obfuscated`.
A change has also been made to the directory creation for the zip file as it before used '\' and now it uses '/'. (last commit)
I have attached a link in the description in commit 12fa245.
To test I created new addresses in IIOP, Network Listeners and JMS Hosts, leaving some values default.
command used to test:
```
./asadmin collect-diagnostics
```

FISH-8177 obfuscate ip addresses hostnames in domain xml payara6

---

src/main/java/fish/payara/extras/diagnostics/util/DomainXmlUtil.java

I have added the keyword `default-principal-password` keyword so that if it is included in the `domain.xml` file, it will obfuscate the password.

FISH-9755 added keyword so default principle password is obfuscated.

---

src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java
src/main/java/fish/payara/extras/diagnostics/util/DomainXmlUtil.java

Previously, bind_dn_password was not obfuscated in the domain xml. 
I have made changes to the `DomainXmlUtil` by creating a new function called `obfuscateElementAttribute` which  improves the readability of the program as the list of node elements was getting too long so I made it into a function as they all had the same functionality. 
I have created a private static final for the bind_dn_password keyword and included it in obfuscation. I have also included the URL keyword in the function  `obfuscateAddressAndHost` as the url for the LDAP needs to be obfuscated.
Finally, I have made changes to the `LogCollector` as previously as a result of a change I had made, it did not create the sub folder for the access logs. This is now working.

FISH-9818 diagnostic tool ldap bind dn password not obfuscated

---

src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java
src/main/java/fish/payara/extras/diagnostics/util/DomainXmlUtil.java

(Payara6) Previously, bind_dn_password was not obfuscated in the domain xml. 
I have made changes to the `DomainXmlUtil` by creating a new function called `obfuscateElementAttribute` which  improves the readability of the program as the list of node elements was getting too long so I made it into a function as they all had the same functionality. 
I have created a private static final for the bind_dn_password keyword and included it in obfuscation. I have also included the URL keyword in the function  `obfuscateAddressAndHost` as the url for the LDAP needs to be obfuscated.
Finally, I have made changes to the `LogCollector`. When the logs are collected, the program will create a folder called logs for  the server and notification logs and then create another folder called access just for …

FISH-9818 diagnostic tool ldap bind dn password not obfuscated payara6

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/DomainXmlCollector.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java
src/main/java/fish/payara/extras/diagnostics/util/Obfuscation.java

I have implemented obfuscation for the logs. The `LogCollector` class calls the `Obfuscation` class which contains the functionality involved with obfuscating files. 
In the `LogCollector` I have updated the constructors to include the `CollectorService` as I needed to pass the boolean variable `obfuscateDomainXml` as to use it as a way to indentify if the obfuscation parameter is set to true which is then used in the if statement in the function `visitFile` which will lead to the function created in `Obfuscation`.
The `obfuscateLogData` function uses a regex to identify different IP Addresses and checks to see if it is equal to the default address which is `0.0.0.0`. It then goes throw the log trying to match a key from the map `hostReplacements` and rewriting the value accordingly.

FISH-9754 Implemented obfuscation for logs using regex.

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/JVMCollector.java
src/main/java/fish/payara/extras/diagnostics/util/DomainUtil.java

As explained in the Remote Instance design page.
**_Changes made to the `CollectorService`:_**
The `CollectorService` has been changed to look for remote instances. The `ExecuteCollection` has been changed so it calls a function called `getInstancesList` which will use an asadmin command `list-nodes --long` and `list-instances` to populate two fields. `instancesWithType`, which will contain a map of the instance name and its respective node type ("CONFIG" or "SSH") and `targetLists` which will contain a list of all the instances.
The `getInstancesList` function was previously named `getInstanceRoot` which would only get the root directory of the instance. This forces the Diagnostic Tool to only look for local instances and so it has been changed to fit the new purpose.
The switch …

FISH-10118 FISH-10119 collect JVM/Thread dump from a remote ssh node

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/JVMCollector.java
src/main/java/fish/payara/extras/diagnostics/util/DomainUtil.java

**(Payara 6)**
As explained in the Remote Instance design page.
**_Changes made to the `CollectorService`:_**
The `CollectorService` has been changed to look for remote instances. The `ExecuteCollection` has been changed so it calls a function called `getInstancesList` which will use an asadmin command `list-nodes --long` and `list-instances` to populate two fields. `instancesWithType`, which will contain a map of the instance name and its respective node type ("CONFIG" or "SSH") and `targetLists` which will contain a list of all the instances.
The `getInstancesList` function was previously named `getInstanceRoot` which would only get the root directory of the instance. This forces the Diagnostic Tool to only look for local instances and so it has been changed to fit the new purpose.
The …

FISH-10118 collect jvm reports from ssh instance

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java

I have revamped the `LogCollector` class so it utilises the command `collect-log-files`.
What the command does is it collects the log files from local or remote instances and stores it in a zip file in payara5/glassfish/domains/domain1/collected-logs. The LogCollector then uses the command output to determine the location of the file and unzips the file and copies into the respective folder.
It creates the log folders accordingly depending if there is an instance or not.
If a target is used (`./asadmin collect-diagnostics --target instance`) then it will use the target and attach it to the `programOptions` which is then used for the command.
I have also added some error handling on the `CollectorService`  as if there are no instances it should still collect the logs for the server. A few …

FISH-10120 collect logs from a remote ssh instance

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/HeapDumpCollector.java

I have updated the `HeapDumpCollector` so that it generates and collects the heap dump from remote nodes.
I have created a variable that calls a function in the `CollectorService` which returns the target type of the current target (`CONFIG` = Local, `SSH` = Remote).
These values are then used to determine if the `outputdir` for the `generate-heap-dump` command will be the local directory or, if the target is SSH, it will use the `nodeInstallationDirectory` variable which will generate the heap dump in the remote machine.
After the command is executed, the file name is extracted if the target is SSH, which will then send this information to the `downloadFileUsingSCP` function. This function uses SCP to go to the file directory and copy the file to the Diagnostics folder. After the …

FISH-10121 collect heap dump from remote ssh node

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/HeapDumpCollector.java

**Payara 6**
I have updated the `HeapDumpCollector` so that it generates and collects the heap dump from remote nodes.
I have created a variable that calls a function in the `CollectorService` which returns the target type of the current target (`CONFIG` = Local, `SSH` = Remote).
These values are then used to determine if the `outputdir` for the `generate-heap-dump` command will be the local directory or, if the target is SSH, it will use the `nodeInstallationDirectory` variable which will generate the heap dump in the remote machine.
After the command is executed, the file name is extracted if the target is SSH, which will then send this information to the `downloadFileUsingSCP` function. This function uses SCP to go to the file directory and copy the file to the Diagnostics folder. …

FISH-10121 collect heap dump from remote ssh nodes

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/HeapDumpCollector.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java

I have changed the `LogCollector` to collect the access and notification logs.
**Access Logs**
As the `collect-log-files` command does not target folders in the logs folder, for example `logs\access`. I used SCP to download the file from the host machine if it is of `SSH`. If it is `CONFIG` then it will collect the file manually from the logs folder.
**Notification Log**
As notification logs are already collected, I have changed it so if the `collectNotificationLogs` is false, it will collect all the logs and then delete the notification log. I have also done this with the server logs as well by using a case statement.

FISH-10375 implement access and notification log collection from remote ssh instance

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/HeapDumpCollector.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java

**Payara 6**
I have changed the `LogCollector` to collect the access and notification logs.
**Access Logs**
As the `collect-log-files` command does not target folders in the logs folder, for example `logs\access`. I used SCP to download the file from the host machine if it is of `SSH`. If it is `CONFIG` then it will collect the file manually from the logs folder.
**Notification Log**
As notification logs are already collected, I have changed it so if the `collectNotificationLogs` is false, it will collect all the logs and then delete the notification log. I have also done this with the server logs as well by using a case statement.

FISH-10375 implement access and notification log collection from remote ssh instance Payara 6

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

**Payara 6**
Changed domain.xml collection so both ssh and local nodes can collect from it. SSH nodes collect the domain.xml from the server whereas the local nodes collect from their own respective folder. (They are both the same anyways).

FISH-10559 added domain.xml collection for SSH nodes.

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LocalLogCollector.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/LogCollector.java

I have added the old code as a new class as to not overcrowd the existing `LogCollector`. 
I have created some error messages to notify the user that the server is offline and only the `local server logs` and `domain.xml` will be collected. This will determine if the variable `serverIsOn` is true or false which will guide the `activeCollectors` to see if they should use the `LogCollector` which uses the `remote commands` or the `LocalLogCollector`.
I think this is a better option as without the server being on, we are not able to find what instances there are without completely reverting back to the old code, which at that point, makes using the remote commands a bit redundant.
I think it makes sense that if the server is off, then it should only collect the `domain.xml` and the `server …

FISH-10544 Unable to collect logs when the domain is off

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

**Payara 6**
Added a null check to make sure that the --target exists and that `targetType` is not null.

FISH-10817 --target does not exist

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

If the target in `collect-diagnostics --target thisDoesNotExist` does not exist, it will send an error and stop the collection of diagnostics.

FISH-10817 --target does not exist check

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java
src/main/java/fish/payara/extras/diagnostics/collection/collectors/HeapDumpCollector.java

I have added collection for these 3 for domain. I wrapped every `targetType` reference in an if `targetType != null` as if it is collecting for the domain, it would throw an error since the domain is not "CONFIG" or "SSH".

FISH-10826 Heap, Thread and JVM Report not collected by domain

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

Remote instances got NPE when trying to create a log path which is meant for local instances.
I have created a variable to hold the log path and added an if statement to make sure it only gets populated if the `instanceType` is "CONFIG"

FISH-10835 Remote instances fail collecting logs due to NPE

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

I have added an error message to appear if the authentication of the domain fails. This sets a variable to false and in turn returns 1 which causes the program to stop.
This displays the error message relating to the authentication and another log which shuts down the command.

FISH-10872 Failing authentication should stop the collection

---

src/main/java/fish/payara/extras/diagnostics/collection/CollectorService.java

The issue isn't that the command executes against the wrong domain. It is that the remote command used to list all the instances gathers instances from domain1 and domain2 (any other domain). It then displays them no matter the scenario which means that it logs all the instances found even if domain2 is empty.
I have changed this so it only displays instances that are part of the domain being collected.

FISH-10977 Command Executes against Non-Target Domain
